blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("database/", include("database_where.urls", namespace="database_where")),

]

database_where/urls.py
from django.urls import path
from . import views

from django.contrib.sitemaps.views import sitemap
from database_where.sitemaps import PostSitemap
from .feeds import LatestPostsFeed

sitemaps = {
    'posts': PostSitemap,
}

"""определяется именное пространство приложения"""
app_name = 'blog'

urlpatterns = [
    # представления поста
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

database_where/models.py
from django.contrib.auth.models import User
from django.db import models as m
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(m.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .filter(status=Post.Status.PUBLISHED)


class Post(m.Model):
    class Status(m.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = m.CharField(max_length=250)
    slug = m.SlugField(max_length=250, unique_for_date='publish')
    author = m.ForeignKey(User, on_delete=m.CASCADE,
                          related_name="blog_posts")
    body = m.TextField()
    publish = m.DateTimeField(default=timezone.now)
    created = m.DateTimeField(auto_now_add=True)
    update = m.DateTimeField(auto_now=True)
    status = m.CharField(max_length=2,
                         choices=Status.choices,
                         default=Status.DRAFT)
    """
    Менеджер tags позволит добавлять, извлекать и удалять теги из объектов
    """
    tags = TaggableManager()

    objects = m.Manager()  # менеджер, применяемый по умолчанию
    published = PublishedManager()  # конкретно-прикладной менеджер

    class Meta:
        ordering = ["-publish"]
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        indexes = [
            m.Index(fields=["-publish"])
        ]

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(m.Model):
    post = m.ForeignKey(Post,
                        on_delete=m.CASCADE,
                        related_name='комментарии')
    name = m.CharField(max_length=80)
    email = m.EmailField()
    body = m.TextField()
    created = m.DateTimeField(auto_now_add=True)
    updated = m.DateTimeField(auto_now=True)
    active = m.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    indexes = [
        m.Index(fields=['created']),
    ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

database_where/forms.py
from django import forms
from django.contrib.postgres.search import SearchVector
from django.shortcuts import render

from database_where.models import Comment, Post


class EmailPostForm(forms.Form):
    Имя = forms.CharField(max_length=25)
    Почта = forms.EmailField()
    Адрес_получателя = forms.EmailField()
    Комментарии = forms.CharField(required=False,
                                  widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

database_where/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db.models import Count
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from database_where.forms import EmailPostForm, CommentForm, SearchForm

from database_where.models import Post
from django.core.paginator import Paginator, EmptyPage, \
    PageNotAnInteger


def post_list(request, tag_slug=None):
    """
    render - функцию сокращенного доступа
    """
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Постраничная разбивка с 3 постами на страницу
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        """
        Если page_number не целое число, то
        выдать первую страницу
        """
        posts = paginator.page(1)
    except EmptyPage:
        """
        Если page_number находится вне диапазона, то
        выдать последнюю страницу
        """
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  "database_where/post/list.html",
                  {"posts": posts,
                   'tag': tag}
                  )


class PostListView(ListView):
    """
    Альтернативное представление списка постов
    """
    queryset = Post.published.all()  # model=Post
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'database_where/post/list.html'


def post_detail(request, post, year, month, day):
    # try:
    #     post = Post.published.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404("No Post found.")
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Список активных комментариев к этому посту
    comments = post.комментарии.filter(active=True)
    # Форма для комментирования пользователями
    form = CommentForm()

    # Список схожих постов
    post_tags_ids = post.tags.values_list('id',
                                          flat=True)  # flat=True, чтобы получить одиночные значения, такие как [1, 2]
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  "database_where/post/detail.html",
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts, }
                  )


def post_share(request, post_id):
    # Извлечь пост по идентификатору id
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['Имя']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['Имя']}\'комментарий: {cd['Комментарии']}"
            send_mail(subject, message, 'modaravvv@gmail.com',
                      [cd['Адрес_получателя']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'database_where/post/share.html', {'post': post,
                                                              'form': form,
                                                              'sent': sent})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post,
                             id=post_id,
                             status=Post.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.post = post
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'database_where/post/comment.html',
                  {'post': post,
                   'form': form,
                   'comment': comment})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Поиск по триграммному сходству
            # if form.is_valid():
            #  query = form.cleaned_data['query']
            #  results = Post.published.annotate(
            #  similarity=TrigramSimilarity('title', query),
            #  ).filter(similarity__gt=0.1).order_by('-similarity')

            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')

            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank' """классифицировать""")
    return render(request,
                  'database_where/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

database_where/templates/database_where/post/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>

<body>


<div id="content">
    <div align="center">{% block content %}</div>
        <div align="center">{% endblock %}</div>
</div>
<div id="sidebar">
    <h2>
        <div align="center">Мой блог</div>
    </h2>
    <p>
    <div align="center">Это мой блог</div>
    Я написал {% total_posts %} сообщений
    <p>
        <a href="{% url "blog:post_feed" %}">
            Подпишитесь на мою RSS-ленту
        </a>
    </p>
    <h3>Последние посты</h3>
    {% show_latest_posts 3 %}
    <h3>Самые комментируемые посты</h3>
    {% get_most_commented_posts as most_commented_posts %}
    <ul>
        {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>

</div>
</body>
</html>

database_where/templates/database_where/post/comment.html
{% extends "database_where/post/base.html" %}

{% block title %}Добавить комментарий{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Ваш комментарий был добавлен</h2>
        <p><a href="{{ post.get_absolute_url }}">Вернуться к посту</a></p>
    {% else %}
        {% include "database_where/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

database_where/templates/database_where/post/detail.html
{% extends "database_where/post/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "database_where:post_share" post.id %}">
            Поделиться этой записью
        </a>
    </p>
    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Подобных постов пока нет
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} комментариев {{total_comments|pluralize}}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Комментарий {{ forloop.counter }} {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Нет комментариев</p>
    {% endfor %}
    {% include "database_where/post/includes/comment_form.html" %}

{% endblock %}

database_where/templates/database_where/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

database_where/templates/database_where/post/list.html
{% extends "database_where/post/base.html" %}
{% load blog_tags %}

{% block title %}Мой блог{% endblock %}
{% block content %}
    <h1>Мой блог</h1>
    {% if tag %}
        <h2>Посты с тегами "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "database_where:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}

        </p>
        <p class="date">
        Опубликовано {{ post.publish }}  {{ post.author }}
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

database_where/templates/database_where/post/search.html
{% extends "database_where/post/base.html" %}
{% load blog_tags %}

{% block title %}Поиск{% endblock %}

{% block content %}
    {% if query %}
        <h1>Сообщения, содержащие "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найденный {{ total_results }} результат{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>По вашему запросу нет результатов.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Искать снова</a></p>
    {% else %}
        <h1>Поиск сообщений</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

database_where/templates/database_where/post/share.html
{% extends "database_where/post/base.html" %}

{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail успешно отправлено</h1>
        <p>
            "{{ post.title }}" был успешно отправлен
            {{ form.cleaned_data.to }}
        </p>
    {% else %}

        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить e-mail">
        </form>
    {% endif %}
{% endblock %}

{% for field in form %}
    <div>
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}